<?php

namespace Tests\src\Attributes;

use Darken\Attributes\ConstructorParam;
use Darken\Builder\CodeCompiler;
use Darken\Builder\OutputCompiled;
use Darken\Builder\OutputPolyfill;
use Tests\TestCase;

class ConstructorParamTest extends TestCase
{
    public function testConstructor()
    {
        $x = new ConstructorParam('test');
        $this->assertInstanceOf(ConstructorParam::class, $x);
    }
    public function testExtractors()
    {
        $config = $this->createConfig();
        $tmpFile = $this->createTmpFile($config, 'extractcompilertest.php', <<<'PHP'
        <?php
        $x = new 
        class {
            #[\Darken\Attributes\ConstructorParam]
            private $test;

            #[\Darken\Attributes\ConstructorParam('userId')]
            protected $id;
        };
        PHP);

        $file = $this->createInputFile($tmpFile);

        $compiler = new CodeCompiler();

        $output = $compiler->compile($file);        

        $this->assertSame(<<<'PHP'
        <?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        $x = new class($this)
        {
            protected \Darken\Code\Runtime $runtime;
            #[\Darken\Attributes\ConstructorParam]
            private $test;
            #[\Darken\Attributes\ConstructorParam('userId')]
            protected $id;
            public function __construct(\Darken\Code\Runtime $runtime)
            {
                $this->runtime = $runtime;
                $this->test = $this->runtime->getData('constructorParams', 'test');
                $this->id = $this->runtime->getData('constructorParams', 'userId');
            }
        };
        PHP, $output->getCode());

        $outputCompiled = new OutputCompiled($output->getCode(), $file, $config);

        $polyfill = new OutputPolyfill($outputCompiled, $output);

        $polycontent = $polyfill->getBuildOutputContent();

        $this->assertSame(<<<'PHP'
        <?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        namespace Tests\Build\data\generated;

        class extractcompilertest extends \Darken\Code\Runtime
        {
            public function __construct(mixed $test, mixed $userId)
            {
                $this->setData('constructorParams', 'test', $test);
                $this->setData('constructorParams', 'userId', $userId);
            }
            public function renderFilePath(): string
            {
                return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'extractcompilertest.compiled.php';
            }
        }
        PHP, $polycontent);

    }
    
    public function testConstructorParamSorting()
    {
        $this->createCompileTest($this->createConfig(), <<<'PHP'
        <?php
        $x = new 
        class {
            #[\Darken\Attributes\ConstructorParam]
            protected $test;

            public $fromTest;

            public function __construct()
            {
                $this->fromTest = $this->test;
            }
        };
        PHP, <<<'PHP'
        <?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        $x = new class($this)
        {
            protected \Darken\Code\Runtime $runtime;
            #[\Darken\Attributes\ConstructorParam]
            protected $test;
            public $fromTest;
            public function __construct(\Darken\Code\Runtime $runtime)
            {
                $this->runtime = $runtime;
                $this->test = $this->runtime->getData('constructorParams', 'test');
                $this->fromTest = $this->test;
            }
        };
        PHP, <<<'PHP'
        <?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        namespace Tests\Build\data\generated;

        class test extends \Darken\Code\Runtime
        {
            public function __construct(mixed $test)
            {
                $this->setData('constructorParams', 'test', $test);
            }
            public function renderFilePath(): string
            {
                return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test.compiled.php';
            }
        }
        PHP);
    }

    public function testFullQualifiedLeadingSlashForObjectConstructorParam()
    {
        $this->createCompileTest($this->createConfig(), <<<'PHP'
        <?php
        $x = new class {
            #[\Darken\Attributes\ConstructorParam]
            protected \Tests\data\di\Db $test;
        };
        PHP, <<<'PHP'
        <?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        $x = new class($this)
        {
            protected \Darken\Code\Runtime $runtime;
            #[\Darken\Attributes\ConstructorParam]
            protected \Tests\data\di\Db $test;
            public function __construct(\Darken\Code\Runtime $runtime)
            {
                $this->runtime = $runtime;
                $this->test = $this->runtime->getData('constructorParams', 'test');
            }
        };
        PHP, <<<'PHP'
        <?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        namespace Tests\Build\data\generated;

        class test extends \Darken\Code\Runtime
        {
            public function __construct(\Tests\data\di\Db $test)
            {
                $this->setData('constructorParams', 'test', $test);
            }
            public function renderFilePath(): string
            {
                return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test.compiled.php';
            }
        }
        PHP);
    }

    public function testConstructorParamOrderingConsistency()
    {
        // Test case 1: Properties declared in order $alpha, $beta
        $this->createCompileTest($this->createConfig(), <<<'PHP'
        <?php
        $x = new class {
            #[\Darken\Attributes\ConstructorParam('alpha')]
            protected $first;

            #[\Darken\Attributes\ConstructorParam('beta')]
            protected $second;
        };
        PHP, <<<'PHP'
        <?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        $x = new class($this)
        {
            protected \Darken\Code\Runtime $runtime;
            #[\Darken\Attributes\ConstructorParam('alpha')]
            protected $first;
            #[\Darken\Attributes\ConstructorParam('beta')]
            protected $second;
            public function __construct(\Darken\Code\Runtime $runtime)
            {
                $this->runtime = $runtime;
                $this->first = $this->runtime->getData('constructorParams', 'alpha');
                $this->second = $this->runtime->getData('constructorParams', 'beta');
            }
        };
        PHP, <<<'PHP'
        <?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        namespace Tests\Build\data\generated;

        class orderingconsistency1 extends \Darken\Code\Runtime
        {
            public function __construct(mixed $alpha, mixed $beta)
            {
                $this->setData('constructorParams', 'alpha', $alpha);
                $this->setData('constructorParams', 'beta', $beta);
            }
            public function renderFilePath(): string
            {
                return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'orderingconsistency1.compiled.php';
            }
        }
        PHP);

        // Test case 2: Properties declared in REVERSE order $beta, $alpha  
        // The generated constructor should have the SAME parameter order: $alpha, $beta
        $this->createCompileTest($this->createConfig(), <<<'PHP'
        <?php
        $x = new class {
            #[\Darken\Attributes\ConstructorParam('beta')]
            protected $second;

            #[\Darken\Attributes\ConstructorParam('alpha')]
            protected $first;
        };
        PHP, <<<'PHP'
        <?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        $x = new class($this)
        {
            protected \Darken\Code\Runtime $runtime;
            #[\Darken\Attributes\ConstructorParam('beta')]
            protected $second;
            #[\Darken\Attributes\ConstructorParam('alpha')]
            protected $first;
            public function __construct(\Darken\Code\Runtime $runtime)
            {
                $this->runtime = $runtime;
                $this->second = $this->runtime->getData('constructorParams', 'beta');
                $this->first = $this->runtime->getData('constructorParams', 'alpha');
            }
        };
        PHP, <<<'PHP'
        <?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        namespace Tests\Build\data\generated;

        class orderingconsistency2 extends \Darken\Code\Runtime
        {
            public function __construct(mixed $alpha, mixed $beta)
            {
                $this->setData('constructorParams', 'alpha', $alpha);
                $this->setData('constructorParams', 'beta', $beta);
            }
            public function renderFilePath(): string
            {
                return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'orderingconsistency2.compiled.php';
            }
        }
        PHP);
    }
}