<?php

namespace Tests\src\Attributes;

use Tests\TestCase;

class MiddlewareTest extends TestCase
{
    public function testMiddlwareAttributeExtractionTest()
    {
        $this->createCompileTest($this->createConfig(), <<<'PHP'
        <?php
        return new 
        #[\Darken\Attributes\Middleware('test')]
        class {
        };
        PHP, <<<'PHP'
        <?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        return new #[\Darken\Attributes\Middleware('test')] class($this)
        {
            protected \Darken\Code\Runtime $runtime;
            public function __construct(\Darken\Code\Runtime $runtime)
            {
                $this->runtime = $runtime;
            }
        };
        PHP, <<<'PHP'
        <?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

        namespace Tests\Build\data\generated;

        class test extends \Darken\Code\Runtime
        {
            public function __construct()
            {
            }
            public function renderFilePath(): string
            {
                return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test.compiled.php';
            }
        }
        PHP);
    }
}