name: Performance Testing

on: [push, pull_request]

jobs:
  benchmark:
    name: PHPBench on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4', '8.5']
        include:
          - php: '8.5'
            experimental: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: :opcache

      - name: Install dependencies
        run: composer clearcache && composer install --prefer-dist

      - name: Run Benchmarks
        run: vendor/bin/phpbench run benchmark --report=aggregate
