name: PHPStan Test

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring
        tools: composer:v2

    - name: Install dependencies
      run: composer clearcache && composer install --prefer-dist

    - name: Run PHPStan
      run: composer phpstan