name: PHP Composer Test

on: [push, pull_request]

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.3', '8.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xdebug
          ini-values: date.timezone='UTC'
          tools: composer:v2
          coverage: xdebug  # Ensure coverage tools are set up

      - name: Install dependencies
        run: composer clearcache && composer install --prefer-dist

      - name: Run PHPUnit Tests
        run:  ./vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        if: matrix.php == '8.3'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
